### PR TITLE
Fix CLI needing a graphical environment to work

### LINKED ISSUE #11: --export needs a graphical environment to work
I noticed that `--export` needs a graphical environment to work even though no window is created. This is a problem when running it in headless environment, such as CI.

```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
```

### PR DESCRIPTION
**Pull request by Huitsi**
Closes #11 by using a QCoreApplication to process the arguments.
This least hacky solution I could come up with. This way --help and possible future options will work too.
As a bonus, a few more error messages for incorrect CLI usage are included.

### CODE REVIEW

File: src/ui/main.cpp [hunk 1]
```diff
@@ -35,14 +35,24 @@ struct Arguments {
...
+            if (instance.export_) {
+                qCritical() << QApplication::translate("main", "No file given to export.");
+                exit(1);
+            }
             return {};
         }
 
+        if (args.size() > 1) {
+            qWarning() << QApplication::translate(
+                "main", "Too many positional arguments given. Only the first one is used.");
```
Comment (agateau) [inline src/ui/main.cpp]: I would rather stop here: the user most likely made a mistake and the app is not going to do what they expect.

**Review by agateau — CHANGES_REQUESTED** [review]
Just made a minor remark. Looks very good otherwise. It's nice to be able to use the command-line  parser without having to parse argv ourselves, let's just hope creating a QCoreApplication and then a QApplication does not bite us in the future :)

**Comment by Huitsi** [comment]
Well, I discovered the first issue with this approach, as the QApplication GUI wasn't loading. Oddly enough it worked fine yesterday. Anyway, destroying the QCoreApplication before creating the QApplication seems to fix it.

File: src/ui/main.cpp [hunk 2]
```diff
@@ -166,6 +166,8 @@ int main(int argc, char* argv[]) {
         return exportSound(maybeArgs.value());
     }
 
+    cli.~QCoreApplication();
```
Comment (agateau) [inline src/ui/main.cpp]: Hu, that's scary :) You can avoid this by storing the QCoreApplication in a std::unique_ptr. You would need to `#include <memory>`, then start of `main()` would go like this:

```cpp
auto cli = std::make_unique<QCoreApplication>(argc, argv);
QCommandLineParser parser;
setupCommandLineParser(&parser);
parser.process(cli.get);
// ...
```

Then to delete our instance:

```cpp
cli.reset();
```

Comment (Huitsi) [reply src/ui/main.cpp]: I have to admit I don't see what's scary about calling a destructor or how this wrapper makes things better.

Comment (agateau) [reply src/ui/main.cpp]: What scares me is the idea of having an instance hanging around after its destructor has been called. Admittedly it's not used here, but I don't like it.

Comment (agateau) [reply src/ui/main.cpp]: This stackoverflow answer gives more reasons why it's not a good idea: https://stackoverflow.com/q/65797371

Comment (Huitsi) [reply src/ui/main.cpp]: Okay, thanks for the explanation.

**Review by agateau — APPROVED** [review]

**Comment by agateau** [comment]
Looks good now, thanks a lot for your work!
